services:
  backend:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY_BACKEND}:${IMAGE_TAG}
    expose:
      - "8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_JWT_PUBLIC_KEY=${SUPABASE_JWT_PUBLIC_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIPE_UNTAB_PRICE_ID=${STRIPE_UNTAB_PRICE_ID}
      - POSTGRES_DATABASE_URL=${POSTGRES_DATABASE_URL}
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    deploy:
      resources:
        limits:
          cpus: "0.50" # 50% of a CPU core
          memory: 512M # 512 MB memory
        reservations:
          memory: 256M # 256 MB memory reservation

  frontend:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY_FRONTEND}:${IMAGE_TAG}
    expose:
      - "3000"
    deploy:
      resources:
        limits:
          cpus: "0.50" # 50% of a CPU core
          memory: 512M # 512 MB memory
        reservations:
          memory: 256M # 256 MB memory reservation

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend
    deploy:
      resources:
        limits:
          cpus: "0.25" # 25% of a CPU core
          memory: 256M # 256 MB memory
        reservations:
          memory: 128M # 128 MB memory reservation

volumes:
  letsencrypt:
    external: true
